#!/bin/bash
# Generate NSDR voice prompts as a single C header.
#
# Pipeline per clip:
#   say (macOS TTS, Tingting voice) → AIFF
#   afconvert → 8kHz mono 16-bit PCM WAV
#   xxd → C uint8_t array (WAV with header — M5Unified.playWav parses it)
#
# Output: src/nsdr_audio.h
#
# Re-run any time you change the script text.

set -e
cd "$(dirname "$0")/.."

VOICE="Tingting"
OUT_DIR="$(mktemp -d)"
OUT_HEADER="src/nsdr_audio.h"

# Format: ID|text
# Keep order — the NSDR scheduler indexes clips by ID.
CLIPS=(
    "intro|找一个舒服的姿势，闭上眼睛"
    "breathe|深吸一口气，慢慢呼出来"
    "feet|把注意力放到双脚，感受它们的重量"
    "legs|现在是小腿和大腿，让它们完全放松"
    "belly|感受腹部，随呼吸轻轻起伏"
    "chest|胸口和肩膀，让紧绷融化"
    "arms|手臂从指尖到肩膀，彻底松开"
    "neck|脖子、下巴，让牙齿微微分开"
    "face|整张脸放松，眉心舒展"
    "whole|现在感受整个身体的存在"
    "return|开始注意周围的声音，活动手指和脚趾"
    "end|深吸一口气，慢慢睁开眼睛"
)

echo "// Auto-generated by tools/generate_nsdr_audio.sh — do not edit by hand"  > "$OUT_HEADER"
echo "// Voice: macOS \`say -v $VOICE\`. Format: 8kHz mono 16-bit PCM (WAV)"    >> "$OUT_HEADER"
echo "#pragma once"                                                              >> "$OUT_HEADER"
echo "#include <stdint.h>"                                                       >> "$OUT_HEADER"
echo                                                                             >> "$OUT_HEADER"

declare -a CLIP_IDS

for entry in "${CLIPS[@]}"; do
    id="${entry%%|*}"
    text="${entry#*|}"
    CLIP_IDS+=("$id")

    aiff="$OUT_DIR/$id.aiff"
    wav="$OUT_DIR/$id.wav"

    echo "  [$id] $text"
    say -v "$VOICE" -o "$aiff" "$text"
    afconvert -f WAVE -d LEI16@8000 -c 1 "$aiff" "$wav" 2>/dev/null

    # Emit as C array. Default xxd output uses `unsigned char` without const,
    # which lands in DRAM. Patch on the fly to const + flash-resident.
    xxd -i -n "nsdr_clip_${id}" "$wav" \
        | sed -E -e 's/^unsigned char/static const uint8_t/' \
                 -e 's/^unsigned int/static const uint32_t/' \
        >> "$OUT_HEADER"
    echo >> "$OUT_HEADER"
done

# Build a lookup table so the scheduler can index by enum
echo "// ── Clip index table ──"                                                 >> "$OUT_HEADER"
echo "struct NsdrClip { const uint8_t* data; uint32_t len; };"                   >> "$OUT_HEADER"
echo "static const NsdrClip nsdr_clips[] = {"                                    >> "$OUT_HEADER"
for id in "${CLIP_IDS[@]}"; do
    echo "    { nsdr_clip_${id}, nsdr_clip_${id}_len },"                         >> "$OUT_HEADER"
done
echo "};"                                                                        >> "$OUT_HEADER"
echo "static constexpr uint8_t NSDR_CLIP_COUNT = ${#CLIP_IDS[@]};"               >> "$OUT_HEADER"
echo                                                                             >> "$OUT_HEADER"

# Also emit enum for readable indexing in C code
echo "enum NsdrClipId : uint8_t {"                                               >> "$OUT_HEADER"
i=0
for id in "${CLIP_IDS[@]}"; do
    upper=$(echo "$id" | tr 'a-z' 'A-Z')
    echo "    NSDR_${upper} = ${i},"                                             >> "$OUT_HEADER"
    i=$((i + 1))
done
echo "};"                                                                        >> "$OUT_HEADER"

# Summary
total=$(wc -c < "$OUT_HEADER")
echo
echo "Generated $OUT_HEADER  (header size: ${total} bytes)"
echo "Clips: ${#CLIPS[@]}"
rm -rf "$OUT_DIR"
