#!/bin/bash
# Generate NSDR voice prompts as a single C header.
#
# Pipeline per clip:
#   say (macOS TTS, Tingting voice) → AIFF
#   afconvert → 8kHz mono 16-bit PCM WAV
#   xxd → C uint8_t array (WAV with header — M5Unified.playWav parses it)
#
# Output: src/nsdr_audio.h
#
# Re-run any time you change the script text.

set -e
cd "$(dirname "$0")/.."

VOICE="Tingting"
OUT_DIR="$(mktemp -d)"
OUT_HEADER="src/nsdr_audio.h"

# Format: ID|text
# Keep order — the NSDR scheduler indexes clips by ID.
CLIPS=(
    "intro|找一个舒服的姿势，闭上眼睛"
    "breathe|深吸一口气，慢慢呼出来"
    "feet|注意力放到双脚，感受重量"
    "legs|小腿、大腿，彻底放松"
    "belly|腹部跟着呼吸，轻轻起伏"
    "chest|胸口、肩膀，松下来"
    "arms|手臂从指尖到肩膀，松开"
    "face|脖子、脸、整个头部放松"
    "whole|感受整个身体的存在"
    "return|开始注意周围的声音，活动手指脚趾"
    "end|深吸一口气，慢慢睁开眼睛"
)

echo "// Auto-generated by tools/generate_nsdr_audio.sh — do not edit by hand"  > "$OUT_HEADER"
echo "// Voice: macOS \`say -v $VOICE\`. Format: 8kHz mono 16-bit PCM (WAV)"    >> "$OUT_HEADER"
echo "#pragma once"                                                              >> "$OUT_HEADER"
echo "#include <stdint.h>"                                                       >> "$OUT_HEADER"
echo                                                                             >> "$OUT_HEADER"

declare -a CLIP_IDS

for entry in "${CLIPS[@]}"; do
    id="${entry%%|*}"
    text="${entry#*|}"
    CLIP_IDS+=("$id")

    aiff="$OUT_DIR/$id.aiff"
    raw_wav="$OUT_DIR/${id}_raw.wav"
    wav="$OUT_DIR/$id.wav"

    echo "  [$id] $text"
    say -v "$VOICE" -r 175 -o "$aiff" "$text"
    afconvert -f WAVE -d LEI16@8000 -c 1 "$aiff" "$raw_wav" 2>/dev/null
    # macOS `say` outputs at ~-12 to -18 dBFS — too quiet for the StickS3
    # speaker. Loudnorm bumps to broadcast loudness (-12 LUFS) with peak at
    # -0.5 dBFS, plus dynamic compression so quiet phonemes are still audible.
    # Aggressive: -9 LUFS (about 3 dB above podcast standard) plus heavy
    # compression so every syllable hits hard on the tiny StickS3 speaker.
    # Final stage: a hard volume bump and limiter to prevent clipping.
    ffmpeg -y -loglevel error -i "$raw_wav" \
        -af "loudnorm=I=-9:LRA=4:tp=-0.3,acompressor=ratio=4:attack=3:release=60,volume=2dB,alimiter=limit=0.97" \
        -ar 8000 -ac 1 -sample_fmt s16 "$wav"

    # Emit as C array. Default xxd output uses `unsigned char` without const,
    # which lands in DRAM. Patch on the fly to const + flash-resident.
    xxd -i -n "nsdr_clip_${id}" "$wav" \
        | sed -E -e 's/^unsigned char/static const uint8_t/' \
                 -e 's/^unsigned int/static const uint32_t/' \
        >> "$OUT_HEADER"
    echo >> "$OUT_HEADER"
done

# Build a lookup table so the scheduler can index by enum
echo "// ── Clip index table ──"                                                 >> "$OUT_HEADER"
echo "struct NsdrClip { const uint8_t* data; uint32_t len; };"                   >> "$OUT_HEADER"
echo "static const NsdrClip nsdr_clips[] = {"                                    >> "$OUT_HEADER"
for id in "${CLIP_IDS[@]}"; do
    echo "    { nsdr_clip_${id}, nsdr_clip_${id}_len },"                         >> "$OUT_HEADER"
done
echo "};"                                                                        >> "$OUT_HEADER"
echo "static constexpr uint8_t NSDR_CLIP_COUNT = ${#CLIP_IDS[@]};"               >> "$OUT_HEADER"
echo                                                                             >> "$OUT_HEADER"

# Also emit enum for readable indexing in C code
echo "enum NsdrClipId : uint8_t {"                                               >> "$OUT_HEADER"
i=0
for id in "${CLIP_IDS[@]}"; do
    upper=$(echo "$id" | tr 'a-z' 'A-Z')
    echo "    NSDR_${upper} = ${i},"                                             >> "$OUT_HEADER"
    i=$((i + 1))
done
echo "};"                                                                        >> "$OUT_HEADER"

# Summary
total=$(wc -c < "$OUT_HEADER")
echo
echo "Generated $OUT_HEADER  (header size: ${total} bytes)"
echo "Clips: ${#CLIPS[@]}"
rm -rf "$OUT_DIR"
